package dao;

import interfaces.CouponDAO;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collection;

import beans.Coupon;
import beans.CouponType;
import connectionPool.ConnectionPoolSingleton;
import exception.DuplicateNameException;
import exception.NoUpdateException;

public class CouponDBDAO implements CouponDAO {

	@Override
	public void createCoupon(Coupon coup) throws DuplicateNameException, SQLException {
Connection con = null;
		
		try {
			con = ConnectionPoolSingleton.getInstance().getConnection();
		
			Statement stat = con.createStatement();
				
			String sql = "INSERT INTO Coupon ( TITLE, START_DATE, END_DATE, AMOUNT, TYPE, MESSAGE, PRICE, IMAGE) VALUES ('" +
					coup.getTitle()			+ "','"	+
					coup.getStartDate()		+ "','"	+
					coup.getEndDate()		+ "','" +
					coup.getAmount()		+ "','"	+
					coup.getType()			+ "','" +
					coup.getMessage()		+ "','" +
					coup.getPrice()			+ "','" +
					coup.getImage()			+ "')";
			
			// When running execute() with a second parameter set to RETURN_GENERATED_KEYS you can get the PK valuse generated by the sql-server
			stat.execute(sql, Statement.RETURN_GENERATED_KEYS );
			
			ResultSet set = stat.getGeneratedKeys();
			set.next();
			
			// Setting the Id of the company to the one received from the server.
			coup.setId( set.getLong(1) );
			

		} catch (SQLException e) {
			if ( e.getMessage().contains("Duplicate")){
				throw new DuplicateNameException("Duplicate coupon title.");
			} else {
				throw e;
			}
		} finally {
			if ( con != null ){
				ConnectionPoolSingleton.getInstance().releaseConnection(con);
			}
		}
		
		
	}

	@Override
	public void removeCoupon(long id) throws SQLException {
		Connection con = null;
		try {
			con = ConnectionPoolSingleton.getInstance().getConnection();
			
			Statement stat = con.createStatement();
					
			String sql = "DELETE FROM Coupon WHERE ID = '" + id + "'";

			stat.execute(sql);
			
			if ( stat.getUpdateCount() == 0 ) {
				System.out.println("Company did not exist in the first place....");
			}


		} catch (SQLException e) {
			e.printStackTrace();
		}finally {
			if ( con != null ){
				ConnectionPoolSingleton.getInstance().releaseConnection(con);
			}
		}
		
		
	}

	@Override
	public void upDateCoupon(Coupon coup) throws SQLException, NoUpdateException {
		
		Connection con = null;
		String sql = null;
	try{
		con = ConnectionPoolSingleton.getInstance().getConnection();
		Statement stat = con.createStatement();
		
		 sql = "UPDATE Coupon SET `END_DATE` = '" + coup.getEndDate()
				+ "', `PRICE` = '" +  coup.getPrice()
				+ "' WHERE ID = '" + coup.getId() + "'";
		 
		 stat.execute(sql);
		
		 if(stat.getUpdateCount() == 0 ){
			throw new NoUpdateException();
		 }
		
	}  catch (SQLException e) {
		throw e;
	}finally {
		if ( con != null ){
			ConnectionPoolSingleton.getInstance().releaseConnection(con);
		}
	}
		
		
		
	}

	@Override
	public Coupon getCoupon(long id) throws SQLException {
		Connection con = null;
		String sql;
		Coupon coupon = new Coupon();
		try{
			con = ConnectionPoolSingleton.getInstance().getConnection();
			Statement stat = con.createStatement();
			
			sql="SELECT * FROM Coupon WHERE ID = '" + id + "'";
			
			stat.execute(sql);
			
			ResultSet set = stat.getResultSet();
			
			if ( set.next() ){
				coupon = new Coupon();
				
				coupon.setId		(	set.getLong		("ID") 			);
				coupon.setTitle		(	set.getString	("TITLE") 		);
				coupon.setStartDate	(	set.getDate		("START_DATE")	);
				coupon.setEndDate	(	set.getDate		("END_DATE") 	);
				coupon.setAmount	(	set.getInt		("AMOUNT")		);
				coupon.setType(CouponType.valueOf(set.getString("TYPE")));
				coupon.setMessage	(	set.getString	("MASSAGE")		);
				coupon.setPrice		(	set.getDouble	("PRICE")		);
				coupon.setImage		(	set.getString	("IMAGE")		);
				
			}
			
			
			
		}catch(SQLException e){
			throw e;
		}finally {
			if ( con != null ){
				ConnectionPoolSingleton.getInstance().releaseConnection(con);
			}
		}
		
		
		return coupon;
	}

	@Override
	public Collection<Coupon> getAllCoupon() throws SQLException {
		Coupon coupon = null;
		Connection con = null;
		String sql;
		Collection<Coupon> coupons = new ArrayList<Coupon>();
		
		try{
			con = ConnectionPoolSingleton.getInstance().getConnection();
			
			Statement stat = con.createStatement();
			
			sql = "SELECT * FROM Coupon";
			
			stat.execute(sql);
			ResultSet set = stat.getResultSet();
			
			while ( set.next() ){
				coupon = new Coupon();
				
				coupon.setId		(	set.getLong		("ID") 			);
				coupon.setTitle		(	set.getString	("TITLE") 		);
				coupon.setStartDate	(	set.getDate		("START_DATE")	);
				coupon.setEndDate	(	set.getDate		("END_DATE") 	);
				coupon.setAmount	(	set.getInt		("AMOUNT")		);
				coupon.setType(CouponType.valueOf(set.getString("TYPE")));
				coupon.setMessage	(	set.getString	("MEASSAGE")		);
				coupon.setPrice		(	set.getDouble	("PRICE")		);
				coupon.setImage		(	set.getString	("IMAGE")		);
				
				coupons.add(coupon);

			}
			
			
		}catch (SQLException e) {
			throw e;
		}finally {
			if ( con != null ){
				ConnectionPoolSingleton.getInstance().releaseConnection(con);
			}
		}
		return coupons;
	}
	
	
	

	@Override
	public Collection<Coupon> getCouponByType(CouponType type) {
		return null;
	}

	@Override
	public void removeAllCompanyCoupons(long Companyid) {
		
	}

}
